background {
    monitor =
    path = ~/.config/hypr/hong-kong-night.jpg
    blur_passes = 2
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_center = true
    fade_on_empty = true
    placeholder_text = <span foreground="##cdd6f4">Password...</span>
    position = 0, -50
    halign = center
    valign = center
}
